#file: noinspection SpellCheckingInspection
run:
  concurrency: 4
  modules-download-mode: readonly

# https://golangci-lint.run/usage/configuration/#linters-configuration
linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - ginkgolinter
    - gocritic
    - gocyclo
    - goimports
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - misspell
    - mnd
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - promlinter
    - revive
    - sloglint
    - staticcheck
    - tagliatelle
    - usetesting
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-names:
      - db
      - err
  govet:
    enable-all: true
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: dot-imports
        disabled: true
